alias ctl=systemctl
alias gt=gnome-terminal
alias ev=ebook-viewer
alias nu=nautilus
alias py=python
alias da=django-admin
alias dsp="da startproject"
alias dsa="dm startapp"
alias dmer="python manage.py"
alias dmm="dmer makemigrations"
alias dm="dmer migrate"
alias j=jettyrun
alias drs="dmer runserver"
alias dcs="dmer createsuperuser"
alias chrm=pycharm-community
alias .brc=.bashrc
alias .drc=.desktoprc
alias m=./mvnw
alias b=". ~/.bashrc"
alias .d=.desktop
alias pb=pdfbook
alias e=evince
alias jb=intellij-idea-community
alias jettyrun="java -jar $JETTY_HOME/start.jar"
alias j=jettyrun
alias jr="mvn package jetty:run"
alias c=clear
